import type { CollectionConfig } from 'payload'
import { isAdmin } from '../access/isAdmin'

// SUMMARIZED EPISODE MEMORY.
// This is the layer retrieval actually reads from -- never raw
// Events, never a full conversation transcript. Each episode is a
// short, human-readable claim about a contact, and it is either:
//   - system-generated by a deterministic rule in
//     src/lib/memory/summarize.ts (createdBy: "system_rule"), or
//   - written directly by staff (createdBy: "staff").
// Nothing here is written by an LLM deciding on its own what's worth
// remembering -- that's the "uncontrolled autonomous learning" the
// architecture explicitly defers. `reviewed` starts false; staff
// confirm or delete before it's trusted by getContactMemory().
export const Episodes: CollectionConfig = {
  slug: 'episodes',
  admin: {
    useAsTitle: 'summary',
    defaultColumns: ['summary', 'contact', 'tag', 'reviewed', 'createdBy'],
    description: 'Reviewed, human-readable memory. The only layer the retrieval hook reads from.',
  },
  access: {
    create: isAdmin,
    read: isAdmin,
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    { name: 'contact', type: 'relationship', relationTo: 'contacts', required: true },
    {
      name: 'summary',
      type: 'textarea',
      required: true,
      admin: { description: 'One or two plain-language sentences. E.g. "Visited Chapter 7 pages 4x in 7 days, never called."' },
    },
    {
      name: 'tag',
      type: 'select',
      required: true,
      options: [
        'repeated_interest',
        'form_abandon',
        'after_hours_request',
        'contact_preference',
        'converted',
        'other',
      ],
    },
    { name: 'relatedEvents', type: 'relationship', relationTo: 'events', hasMany: true },
    {
      name: 'createdBy',
      type: 'select',
      required: true,
      defaultValue: 'system_rule',
      options: ['system_rule', 'staff'],
      admin: { description: 'Explainability: was this auto-generated by a deterministic rule, or written by a person?' },
    },
    {
      name: 'reviewed',
      type: 'checkbox',
      defaultValue: false,
      admin: { description: 'Staff confirms before this episode is treated as trustworthy by the retrieval layer.' },
    },
  ],
}
